# Mapping of team abbreviations to their logo URLs
team_logos = {
    "ATL": "https://content.sportslogos.net/logos/6/220/thumbs/22091682022.gif",
    "WAS": "https://upload.wikimedia.org/wikipedia/en/0/02/Washington_Wizards_logo.svg",
    "CHA": "https://upload.wikimedia.org/wikipedia/en/c/c4/Charlotte_Hornets_%282014%29.svg",
    "ATL": "https://upload.wikimedia.org/wikipedia/en/2/24/Atlanta_Hawks_logo.svg",
    "MIA": "https://upload.wikimedia.org/wikipedia/en/f/fb/Miami_Heat_logo.svg",
    "ORL": "https://upload.wikimedia.org/wikipedia/en/1/10/Orlando_Magic_logo.svg",
    "NY": "https://upload.wikimedia.org/wikipedia/en/2/25/New_York_Knicks_logo.svg",
    "PHI": "https://upload.wikimedia.org/wikipedia/en/0/0e/Philadelphia_76ers_logo.svg",
    "BKN": "https://upload.wikimedia.org/wikipedia/commons/4/44/Brooklyn_Nets_newlogo.svg",
    "BOS": "https://upload.wikimedia.org/wikipedia/en/8/8f/Boston_Celtics.svg",
    "TOR": "https://upload.wikimedia.org/wikipedia/en/3/36/Toronto_Raptors_logo.svg",
    "CHI": "https://upload.wikimedia.org/wikipedia/en/6/67/Chicago_Bulls_logo.svg",
    "CLE": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cleveland_Cavaliers_logo.svg/1024px-Cleveland_Cavaliers_logo.svg.png",
    "IND": "https://upload.wikimedia.org/wikipedia/en/1/1b/Indiana_Pacers.svg",
    "DET": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Logo_of_the_Detroit_Pistons.svg",
    "MIL": "https://upload.wikimedia.org/wikipedia/en/4/4a/Milwaukee_Bucks_logo.svg",
    "MIN": "https://upload.wikimedia.org/wikipedia/en/c/c2/Minnesota_Timberwolves_logo.svg",
    "UTA": "https://upload.wikimedia.org/wikipedia/en/5/52/Utah_Jazz_logo_2022.svg",
    "OKC": "https://upload.wikimedia.org/wikipedia/en/5/5d/Oklahoma_City_Thunder.svg",
    "POR": "https://upload.wikimedia.org/wikipedia/en/2/21/Portland_Trail_Blazers_logo.svg",
    "DEN": "https://upload.wikimedia.org/wikipedia/en/7/76/Denver_Nuggets.svg",
    "MEM": "https://upload.wikimedia.org/wikipedia/en/f/f1/Memphis_Grizzlies.svg",
    "HOU": "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Rockets.svg",
    }
